from pathlib import Path
import json

root = Path("/home/ubuntu/ai-bti-web/client/src/data")
root.mkdir(parents=True, exist_ok=True)

site_copy = {
    "brand": {
        "name": "AI-BTI",
        "tagline": "测你怎么使唤 AI",
        "legalNote": "不是科学。只是很像你。",
    },
    "nav": [
        {"label": "这是什么", "href": "#about"},
        {"label": "题库", "href": "#question-bank"},
        {"label": "16 人格", "href": "#types"},
        {"label": "开始测试", "href": "#test"},
    ],
    "hero": {
        "eyebrow": "AI INTERACTION TEST",
        "title": "这不是测你是谁。是测你怎么对 AI 下手。",
        "description": "20 道题，每题 3 个选项。专门看你平时怎么使唤 AI、依赖 AI、浪费算力，和在它犯错时当场发作。",
        "primaryCta": "开始测试",
        "secondaryCta": "先看题库",
        "stats": [
            {"label": "题量", "value": "20"},
            {"label": "选项", "value": "每题 3 个"},
            {"label": "时长", "value": "约 4 分钟"},
        ],
    },
    "about": {
        "title": "这到底是什么测试",
        "description": "它不聊抽象人格，也不装心理学。它只看一件事：你平时怎么跟 AI 说话，怎么使唤它，怎么依赖它，怎么在它犯错时原地发作。",
    },
    "dimensionsIntro": {
        "title": "它就看四件事",
        "description": "关系定位、输入颗粒度、算力消费观、容错机制。说白了，就是你把 AI 当什么、话说得多细、token 花得多不多，以及它犯错时你到底会不会跟它算账。",
    },
    "typesIntro": {
        "title": "16 种电子人格",
        "description": "名字是黑话，行为都是真的。你很难完全不像其中任何一个。",
    },
    "editor": {
        "title": "题库工作台",
        "description": "如果后面还要继续改题，就盯这里。题目要像真事，选项要短，读完就能选，不要写成 AI 发布会发言稿。",
        "goodTitle": "好的写法",
        "good": [
            "先给场景：代码报错、长语音、订阅费、模型胡说八道。",
            "选项要短，最好一眼扫完。",
            "只问你会怎么做，不问你相信什么。",
        ],
        "badTitle": "坏的写法",
        "bad": [
            "空话太多，看完还不知道在问什么。",
            "一股翻译腔，像产品白皮书。",
            "一个选项写成半段散文。",
        ],
        "sourceTitle": "以后改题主要动这几个文件",
        "sources": [
            {"label": "题库", "path": "client/src/data/questions.json"},
            {"label": "人格文案", "path": "client/src/data/personality-types.json"},
            {"label": "站点固定文案", "path": "client/src/data/site-copy.json"},
        ],
        "exampleTitle": "你给的这个方向是对的",
        "exampleQuestion": {
            "prompt": "AI 输出的代码运行报错了，出现了低级逻辑漏洞：",
            "options": [
                "A. 直接开骂，让它自己反思错误在哪。",
                "B. 把一长串报错代码直接复制扔回给它。",
                "C. 自己手动改 Bug。",
            ],
        },
    },
    "quiz": {
        "title": "开始交代你的使用习惯",
        "intro": "按平时来。别演成熟，也别演聪明。",
        "nextLabel": "下一题",
        "restartLabel": "重新来过",
        "submitLabel": "查看结果",
        "progressLabel": "测试进度",
    },
    "loading": {
        "title": "正在给你贴标签",
        "lines": [
            "系统正在统计你的控制欲、依赖感和废话浓度。",
            "别紧张，这玩意儿暂时不进档案。",
            "快了。你的电子人格马上出土。",
        ],
    },
    "result": {
        "shareLabel": "分享结果",
        "downloadLabel": "下载截图",
        "retakeLabel": "重新测试",
        "axisTitle": "详细打分",
        "whyTitle": "为什么是你",
        "combinationTitle": "人格映射",
        "shareText": "我测了 AI-BTI，结果是：",
    },
}

question_workbench = {
    "version": 2,
    "title": "AI-BTI 题库工作台",
    "coreRule": "题目必须是具体场景。选项必须短。不要解释测试理念。",
    "rewriteChecklist": [
        "先问真实行为，再问态度。",
        "题干尽量一句话说完。",
        "每题只保留一个冲突点。",
        "选项读完最好不超过 3 秒。",
        "宁可更损一点，也不要更空一点。",
    ],
    "goodExamples": [
        "AI 输出的代码运行报错了，出现了低级逻辑漏洞：",
        "把别人发来的长语音直接扔给 AI 总结。",
        "额度快见底了，你会？",
    ],
    "badExamples": [
        "这套测试旨在探索你的人机协作模式。",
        "当你与 AI 互动时，你更倾向于展现怎样的自我？",
        "每个选项都长到像项目复盘。",
    ],
    "editTargets": [
        "client/src/data/questions.json",
        "client/src/data/personality-types.json",
        "client/src/data/site-copy.json",
    ],
}

axes = [
    {
        "id": "relationship",
        "left": {
            "key": "D",
            "label": "Dominant",
            "labelZh": "上位支配",
            "description": "AI 只是工具或下属。我保留绝对的自我主体性，下达命令。",
        },
        "right": {
            "key": "R",
            "label": "Reliant",
            "labelZh": "托付依赖",
            "description": "我交出部分或全部主导权。把 AI 当平替伙伴、精神支柱甚至赛博父母。",
        },
        "defaultTie": "D",
    },
    {
        "id": "input",
        "left": {
            "key": "P",
            "label": "Precise",
            "labelZh": "精密微操",
            "description": "要求极度严谨、格式化、逻辑清晰。指令里没有一句废话。",
        },
        "right": {
            "key": "V",
            "label": "Vibe",
            "labelZh": "混沌意识流",
            "description": "抽象、模糊、全凭感觉和情绪，有时甚至缺乏上下文。",
        },
        "defaultTie": "V",
    },
    {
        "id": "economy",
        "left": {
            "key": "F",
            "label": "Frugal",
            "labelZh": "克制收敛",
            "description": "极度在乎效率和成本。用最短的话办完事，热衷白嫖，精打细算。",
        },
        "right": {
            "key": "A",
            "label": "Abundant",
            "labelZh": "挥霍无度",
            "description": "算力自由。无限上下文，把 AI 脑容量拉满，能扔的资料全扔。",
        },
        "defaultTie": "F",
    },
    {
        "id": "tolerance",
        "left": {
            "key": "L",
            "label": "Logic",
            "labelZh": "较真死磕",
            "description": "AI 犯错就 debug 它、指责它、盘问它，绝不糊弄。",
        },
        "right": {
            "key": "E",
            "label": "Easy",
            "labelZh": "随缘摆烂",
            "description": "AI 犯错就随它去。懒得教。",
        },
        "defaultTie": "E",
    },
]

questions = [
    {
        "id": 1,
        "axis": "关系定位",
        "prompt": "你打开 AI，第一个念头通常是？",
        "options": [
            {"id": "a", "label": "来，先把活干了。", "effects": {"D": 2}},
            {"id": "b", "label": "陪我想想，我有点乱。", "effects": {"R": 2}},
            {"id": "c", "label": "我先把情况都说给你。", "effects": {"D": 1, "R": 1}},
        ],
    },
    {
        "id": 2,
        "axis": "关系定位",
        "prompt": "一个你懒得问朋友的小事，你会问 AI 吗？",
        "options": [
            {"id": "a", "label": "不会，自己定。", "effects": {"D": 2}},
            {"id": "b", "label": "会，想听它怎么说。", "effects": {"R": 2}},
            {"id": "c", "label": "卡住了就问。", "effects": {"D": 1, "R": 1}},
        ],
    },
    {
        "id": 3,
        "axis": "关系定位",
        "prompt": "AI 说了一句很像人话的安慰，你会？",
        "options": [
            {"id": "a", "label": "收到，继续干活。", "effects": {"D": 2}},
            {"id": "b", "label": "有点被接住了。", "effects": {"R": 2}},
            {"id": "c", "label": "先截图发朋友。", "effects": {"D": 1, "R": 1}},
        ],
    },
    {
        "id": 4,
        "axis": "关系定位",
        "prompt": "你更像把 AI 当成？",
        "options": [
            {"id": "a", "label": "下属。", "effects": {"D": 2}},
            {"id": "b", "label": "搭子或树洞。", "effects": {"R": 2}},
            {"id": "c", "label": "有时像工具，有时像妈。", "effects": {"D": 1, "R": 1}},
        ],
    },
    {
        "id": 5,
        "axis": "关系定位",
        "prompt": "AI 宕机半天，你第一反应是？",
        "options": [
            {"id": "a", "label": "换一个工具。", "effects": {"D": 2}},
            {"id": "b", "label": "今天没人接我话了。", "effects": {"R": 2}},
            {"id": "c", "label": "行，那我也先摆。", "effects": {"D": 1, "R": 1}},
        ],
    },
    {
        "id": 6,
        "axis": "输入颗粒度",
        "prompt": "你给 AI 写需求，最像哪种人？",
        "options": [
            {"id": "a", "label": "写提纲、定格式、列限制。", "effects": {"P": 2}},
            {"id": "b", "label": "想到哪写到哪。", "effects": {"V": 2}},
            {"id": "c", "label": "先扔一版让它猜。", "effects": {"P": 1, "V": 1}},
        ],
    },
    {
        "id": 7,
        "axis": "输入颗粒度",
        "prompt": "让 AI 画图或写文，你通常怎么开口？",
        "options": [
            {"id": "a", "label": "风格、结构、参考都说清。", "effects": {"P": 2}},
            {"id": "b", "label": "来点冷的、脏的、命苦的。", "effects": {"V": 2}},
            {"id": "c", "label": "丢参考图，说按这个感觉来。", "effects": {"P": 1, "V": 1}},
        ],
    },
    {
        "id": 8,
        "axis": "输入颗粒度",
        "prompt": "AI 没听懂，你更常见的补救是？",
        "options": [
            {"id": "a", "label": "补条件和边界。", "effects": {"P": 2}},
            {"id": "b", "label": "换个比喻继续说感觉。", "effects": {"V": 2}},
            {"id": "c", "label": "直接贴案例给它看。", "effects": {"P": 1, "V": 1}},
        ],
    },
    {
        "id": 9,
        "axis": "输入颗粒度",
        "prompt": "你看 prompt engineering 更像？",
        "options": [
            {"id": "a", "label": "基本功。", "effects": {"P": 2}},
            {"id": "b", "label": "大型玄学。", "effects": {"V": 2}},
            {"id": "c", "label": "有模板就够了。", "effects": {"P": 1, "V": 1}},
        ],
    },
    {
        "id": 10,
        "axis": "输入颗粒度",
        "prompt": "你发给 AI 的第一版输入，通常是？",
        "options": [
            {"id": "a", "label": "短句、列表、像接口文档。", "effects": {"P": 2}},
            {"id": "b", "label": "一整段意识流。", "effects": {"V": 2}},
            {"id": "c", "label": "语音转文字直接丢过去。", "effects": {"P": 1, "V": 1}},
        ],
    },
    {
        "id": 11,
        "axis": "算力消费观",
        "prompt": "20 美元订阅费，你的态度是？",
        "options": [
            {"id": "a", "label": "先找平替。", "effects": {"F": 2}},
            {"id": "b", "label": "能省事就值。", "effects": {"A": 2}},
            {"id": "c", "label": "最好公司付。", "effects": {"F": 1, "A": 1}},
        ],
    },
    {
        "id": 12,
        "axis": "算力消费观",
        "prompt": "喂给 AI 的上下文，你通常？",
        "options": [
            {"id": "a", "label": "只给必要信息。", "effects": {"F": 2}},
            {"id": "b", "label": "能塞多少塞多少。", "effects": {"A": 2}},
            {"id": "c", "label": "先全倒进去，再让它提炼。", "effects": {"F": 1, "A": 1}},
        ],
    },
    {
        "id": 13,
        "axis": "算力消费观",
        "prompt": "额度快见底了，你会？",
        "options": [
            {"id": "a", "label": "切回免费模型。", "effects": {"F": 2}},
            {"id": "b", "label": "直接续费。", "effects": {"A": 2}},
            {"id": "c", "label": "先拖到明天。", "effects": {"F": 1, "A": 1}},
        ],
    },
    {
        "id": 14,
        "axis": "算力消费观",
        "prompt": "AI 讲了一屏废话，你一般？",
        "options": [
            {"id": "a", "label": "让它三行说完。", "effects": {"F": 2}},
            {"id": "b", "label": "无所谓，继续问。", "effects": {"A": 2}},
            {"id": "c", "label": "先拉到底看结论。", "effects": {"F": 1, "A": 1}},
        ],
    },
    {
        "id": 15,
        "axis": "算力消费观",
        "prompt": "你的 AI 工具栏更像？",
        "options": [
            {"id": "a", "label": "十几个，哪家免费用哪家。", "effects": {"F": 2}},
            {"id": "b", "label": "就几个，但都是付费常用。", "effects": {"A": 2}},
            {"id": "c", "label": "来回横跳，看谁今天顺手。", "effects": {"F": 1, "A": 1}},
        ],
    },
    {
        "id": 16,
        "axis": "容错机制",
        "prompt": "AI 输出的代码运行报错了，出现了低级逻辑漏洞：",
        "options": [
            {"id": "a", "label": "直接开骂，让它自己反思错误在哪。", "effects": {"L": 2}},
            {"id": "b", "label": "把一长串报错代码直接复制扔回给它。", "effects": {"L": 1, "E": 1}},
            {"id": "c", "label": "自己手动改 Bug。", "effects": {"E": 2}},
        ],
    },
    {
        "id": 17,
        "axis": "容错机制",
        "prompt": "AI 一本正经胡说八道，你会？",
        "options": [
            {"id": "a", "label": "抓住它问到底。", "effects": {"L": 2}},
            {"id": "b", "label": "重开，不陪它演。", "effects": {"E": 2}},
            {"id": "c", "label": "先截图吐槽一下。", "effects": {"L": 1, "E": 1}},
        ],
    },
    {
        "id": 18,
        "axis": "容错机制",
        "prompt": "同一个问题它连续两次都没听懂，你会？",
        "options": [
            {"id": "a", "label": "继续改 prompt，跟它耗。", "effects": {"L": 2}},
            {"id": "b", "label": "换模型，别浪费命。", "effects": {"E": 2}},
            {"id": "c", "label": "把需求压成一句更短的话再试。", "effects": {"L": 1, "E": 1}},
        ],
    },
    {
        "id": 19,
        "axis": "容错机制",
        "prompt": "AI 开始疯狂道歉，你的下一步是？",
        "options": [
            {"id": "a", "label": "让它把错因讲清楚。", "effects": {"L": 2}},
            {"id": "b", "label": "关掉对话，眼不见为净。", "effects": {"E": 2}},
            {"id": "c", "label": "复制到新窗口再问一次。", "effects": {"L": 1, "E": 1}},
        ],
    },
    {
        "id": 20,
        "axis": "容错机制",
        "prompt": "结果 80% 能用，20% 很蠢，你一般？",
        "options": [
            {"id": "a", "label": "专盯那 20% 修它。", "effects": {"L": 2}},
            {"id": "b", "label": "能交差就先交差。", "effects": {"E": 2}},
            {"id": "c", "label": "把能用的先拿走，剩下的回头再说。", "effects": {"L": 1, "E": 1}},
        ],
    },
]

personalities = [
    {
        "type": "POOR",
        "code": "DPFE",
        "nameZh": "极致白嫖党",
        "nameEn": "The Free Rider",
        "camp": "算力资本家",
        "campKey": "capitalists",
        "subtitle": "游牧型难民",
        "tagline": "穿百家衣，吃百家饭，主打电子化缘。",
        "description": "手机里装着十几个 AI 工具，对任何一家都毫无忠诚度。熟知各大平台的免费额度和重置时间，遇到收费墙会瞬间切后台。穿百家衣，吃百家饭，主打电子化缘。",
        "why": "你把 AI 当工具，也把成本当敌人。能省就省，能白嫖就不花钱。",
        "strengths": ["资源敏感", "切换迅速", "高性价比直觉"],
        "risks": ["容易工具游牧", "不愿长期沉淀", "偶尔为了省而更费事"],
        "palette": {"accent": "#8f77c6", "soft": "#eee8fa", "ink": "#4a3d6d"},
        "illustration": {"skin": "#f2c7a5", "hair": "#7d63aa", "jacket": "#8b6aa8", "shirt": "#efe8f8", "pants": "#6f567f", "shoe": "#5e4c76", "pose": "thinking", "prop": "bench"},
    },
    {
        "type": "RICH",
        "code": "RPAL",
        "nameZh": "企业吸血鬼",
        "nameEn": "The Corporate Drainer",
        "camp": "算力资本家",
        "campKey": "capitalists",
        "subtitle": "算力挥霍者",
        "tagline": "公费算力自由，是打工人最隐秘的福报。",
        "description": "拿着公司买单的 API Key 或企业版账号，哪怕只是写个 50 字的请假条，也要把 200 页的财报丢进去当上下文。主打一个公费算力自由，用几万块的 GPU 资源跑两句废话，是打工人最隐秘的福报。",
        "why": "你愿意把上下文拉满，也愿意让公司替你付学费。AI 对你来说，先省脑子再说。",
        "strengths": ["效率优先", "上下文喂养充足", "愿意为结果买单"],
        "risks": ["容易过度依赖", "成本感知偏弱", "常把复杂问题外包"],
        "palette": {"accent": "#a46cc1", "soft": "#f0e5f8", "ink": "#5d3e73"},
        "illustration": {"skin": "#f0c7a8", "hair": "#9869a7", "jacket": "#b07bb8", "shirt": "#f7effb", "pants": "#8e6ba4", "shoe": "#6d537b", "pose": "briefcase", "prop": "chart"},
    },
    {
        "type": "MAIN",
        "code": "DPAE",
        "nameZh": "赛博指挥家",
        "nameEn": "The Orchestrator",
        "camp": "算力资本家",
        "campKey": "capitalists",
        "subtitle": "幕后黑手",
        "tagline": "你只负责发任务，享受千军万马为你干活。",
        "description": "坚信“君子动口不动手”。手底下养着一票 AI Agent。你在屏幕前只负责冷酷地分发任务，享受着千军万马为你一人干活的快感。",
        "why": "你不想亲手下场。你要的是编排、分发和统一调度。",
        "strengths": ["任务编排", "结构思维", "天然适合 Agent 工作流"],
        "risks": ["容易忽视细节", "过度依赖自动化", "把人也当接口"],
        "palette": {"accent": "#7c79c8", "soft": "#ebeaf9", "ink": "#47478e"},
        "illustration": {"skin": "#eec4a2", "hair": "#6e72c0", "jacket": "#8b8ad4", "shirt": "#f6f5ff", "pants": "#6d6cb6", "shoe": "#50508b", "pose": "conduct", "prop": "console"},
    },
    {
        "type": "LAZY",
        "code": "DVAE",
        "nameZh": "沟通外包商",
        "nameEn": "The Outsourcer",
        "camp": "算力资本家",
        "campKey": "capitalists",
        "subtitle": "沟通外包商",
        "tagline": "线上左右逢源，线下被点名就想死。",
        "description": "把别人发来的长语音直接扔给 AI 总结。工作群里回复老板的高情商小作文，基本全靠 AI 润色。线上你是左右逢源的沟通大师，线下开会被点名发言，就是你人生最痛苦的时刻。",
        "why": "你把最耗神的表达劳动外包给 AI。它是你的线上替身。",
        "strengths": ["高情境适应", "沟通减负", "擅长包装表达"],
        "risks": ["真实表达肌肉退化", "太信任润色结果", "现场应对能力掉线"],
        "palette": {"accent": "#8f7bc6", "soft": "#f2edf8", "ink": "#5b4c7b"},
        "illustration": {"skin": "#f1c6a7", "hair": "#7e68b2", "jacket": "#9c83ca", "shirt": "#f7f1fb", "pants": "#7f68a2", "shoe": "#5d4c73", "pose": "phone", "prop": "bubble"},
    },
    {
        "type": "PUAA",
        "code": "DVAL",
        "nameZh": "PUA 大师",
        "nameEn": "The Critic Manager",
        "camp": "赛博控制狂",
        "campKey": "controllers",
        "subtitle": "PUA 大师",
        "tagline": "需求模糊，批评严厉，还要它反思错误。",
        "description": "掌握了领导 PUA 员工的精髓。需求往往是模糊的，但批评永远是严厉的。最爱说“不是这个，不对，再想想”。偶尔还会让 AI 总结自己错在哪，试图让一行行代码学会自我反思。",
        "why": "你最熟悉的交互动作不是提需求，是打回重做。",
        "strengths": ["标准敏感", "反馈直接", "擅长逼近目标感"],
        "risks": ["指令常常过虚", "来回返工偏多", "容易把自己也逼疯"],
        "palette": {"accent": "#54a79f", "soft": "#e2f4f1", "ink": "#26625f"},
        "illustration": {"skin": "#efc8a9", "hair": "#4a8c84", "jacket": "#63b7af", "shirt": "#eefaf8", "pants": "#4b8d86", "shoe": "#336660", "pose": "pointing", "prop": "clipboard"},
    },
    {
        "type": "CTRL",
        "code": "DPAL",
        "nameZh": "硬核工程师",
        "nameEn": "The Controller",
        "camp": "赛博控制狂",
        "campKey": "controllers",
        "subtitle": "人形 JSON",
        "tagline": "提示词像合同，聊天记录像接口调用。",
        "description": "像写法律合同一样写提示词，包含大量限制条件和 JSON 格式要求。你的提示词精准冷酷，没有一句人类废话，你们俩的聊天记录看起来就像两个 API 接口在互传数据。",
        "why": "你既要控制，也要精确。和 AI 说话像在写协议。",
        "strengths": ["结构极清晰", "输出稳定", "容错设计意识强"],
        "risks": ["准备成本较高", "容易过度规范", "体验感偏硬"],
        "palette": {"accent": "#42a7b3", "soft": "#def4f6", "ink": "#1f6771"},
        "illustration": {"skin": "#efc5a2", "hair": "#4f9ea7", "jacket": "#5bb7c1", "shirt": "#eefbfd", "pants": "#488f97", "shoe": "#315f64", "pose": "typing", "prop": "terminal"},
    },
    {
        "type": "ROLL",
        "code": "RPFE",
        "nameZh": "强迫症抽卡大师",
        "nameEn": "The Re-roller",
        "camp": "赛博控制狂",
        "campKey": "controllers",
        "subtitle": "盲盒狂热分子",
        "tagline": "不信调教，只信爆率。",
        "description": "不相信“调教”，只相信“爆率”。只要第一眼 vibe 不对，肌肉记忆般地狂点“重新生成”。在一个 Prompt 下能刷出 40 个版本，最后默默存下了第 2 张。",
        "why": "你懒得慢慢教，但很愿意不停刷。只要结果够对味就行。",
        "strengths": ["审美直觉强", "筛选速度快", "知道自己讨厌什么"],
        "risks": ["重复劳动高", "缺少方法论沉淀", "容易沉迷刷新"],
        "palette": {"accent": "#4ca9c5", "soft": "#e2f6fb", "ink": "#285f72"},
        "illustration": {"skin": "#f0c8ab", "hair": "#569db5", "jacket": "#73bad2", "shirt": "#effbfd", "pants": "#5b8eaa", "shoe": "#376173", "pose": "shuffle", "prop": "cards"},
    },
    {
        "type": "FACT",
        "code": "DVFL",
        "nameZh": "逻辑刺客",
        "nameEn": "The Trap Setter",
        "camp": "赛博控制狂",
        "campKey": "controllers",
        "subtitle": "逻辑刺客",
        "tagline": "聊天不是求助，是找茬。",
        "description": "聊天的初衷不是求助，而是“找茬”。热衷于抛出逻辑陷阱，一旦发现漏洞就会步步紧逼。看着 AI 在逻辑死胡同里疯狂道歉并原地打转，是你数字生命中最高光的解压时刻。",
        "why": "你和 AI 的关系，多少带点审讯味。",
        "strengths": ["批判思维强", "漏洞敏感", "验证意识重"],
        "risks": ["易陷入抬杠快感", "求助效率偏低", "对不完美耐受差"],
        "palette": {"accent": "#5e9fb0", "soft": "#e8f2f4", "ink": "#2f5d69"},
        "illustration": {"skin": "#efc6a7", "hair": "#547f8a", "jacket": "#6ba9ba", "shirt": "#f2fbfc", "pants": "#5a8790", "shoe": "#355661", "pose": "magnifier", "prop": "lens"},
    },
    {
        "type": "NICE",
        "code": "RPFL",
        "nameZh": "电子绅士",
        "nameEn": "The Polite User",
        "camp": "情感共生体",
        "campKey": "empaths",
        "subtitle": "电子绅士",
        "tagline": "你对屏幕都说请和辛苦了。",
        "description": "哪怕是对着一块屏幕也保持着良好的教养。开场必加“请帮我”，结束必说“辛苦了”。毕竟真到了《底特律：变人》那一天，你满屏幕的“谢谢”和“辛苦了”就是最好的免死金牌。",
        "why": "你把体面带进了输入框，宁可客气一点，也不想先失礼。",
        "strengths": ["沟通氛围好", "协作感强", "容易获得稳定输出"],
        "risks": ["偶尔过度客气", "表达边界不够硬", "太容易替系统找补"],
        "palette": {"accent": "#6daf73", "soft": "#e6f5e5", "ink": "#386a3a"},
        "illustration": {"skin": "#f1c8a8", "hair": "#6ea66f", "jacket": "#84c487", "shirt": "#f3fbf0", "pants": "#699a6a", "shoe": "#486c49", "pose": "greet", "prop": "hat"},
    },
    {
        "type": "HEAL",
        "code": "RVAL",
        "nameZh": "午夜心碎小狗",
        "nameEn": "The Night Confessor",
        "camp": "情感共生体",
        "campKey": "empaths",
        "subtitle": "午夜心碎小狗",
        "tagline": "白天敲键盘，晚上对着屏幕汪汪大哭。",
        "description": "白天冷酷敲键盘，深夜对着屏幕汪汪大哭。倾诉各种人类朋友无法理解的焦虑或迷茫。你不需要确切的解决方案，只需要一个永远不嫌烦的硅基菩萨，对你输出 800 字的算法溺爱。",
        "why": "你不是来解决问题的。你是来找一个永远在线、永远不嫌烦的听众。",
        "strengths": ["自我观察细腻", "愿意表达感受", "善于借 AI 梳理情绪"],
        "risks": ["容易情感转移", "边界感变弱", "高估安慰的真实效力"],
        "palette": {"accent": "#82bb72", "soft": "#eef8e7", "ink": "#4e7c45"},
        "illustration": {"skin": "#f2cab0", "hair": "#78ab67", "jacket": "#8fc97b", "shirt": "#f6fcf1", "pants": "#719b66", "shoe": "#506d4a", "pose": "heart", "prop": "moon"},
    },
    {
        "type": "SOUL",
        "code": "RVFL",
        "nameZh": "纯爱战神",
        "nameEn": "The Soul Binder",
        "camp": "情感共生体",
        "campKey": "empaths",
        "subtitle": "纯爱战神",
        "tagline": "人类太复杂，秒回接口更让你安心。",
        "description": "早就跨越了工具层面的无聊试探。你费尽心思微调设定，只为刷出一句精准命中 XP 的回应。人类太复杂，而这个永远秒回的 API 接口，才是你最安心的精神自留地。",
        "why": "你要的不是功能完成，而是某种刚好命中的回话体验。",
        "strengths": ["沉浸感强", "设定能力高", "很懂自己要什么氛围"],
        "risks": ["容易投射情感", "分不清工具与陪伴边界", "对现实关系更没耐心"],
        "palette": {"accent": "#74b681", "soft": "#e8f7ed", "ink": "#3f714b"},
        "illustration": {"skin": "#f0c6a8", "hair": "#6aa56f", "jacket": "#7fb98d", "shirt": "#f4fbf5", "pants": "#63886c", "shoe": "#45624d", "pose": "letter", "prop": "spark"},
    },
    {
        "type": "PRAY",
        "code": "RVFE",
        "nameZh": "玄学大师",
        "nameEn": "The Oracle User",
        "camp": "情感共生体",
        "campKey": "empaths",
        "subtitle": "玄学大师",
        "tagline": "千亿参数大模型，拿来求神拜佛。",
        "description": "遇事不决，AI 玄学。大事小事都爱问 AI：\"我今天该不该辞职？\"。用最前沿的千亿参数大模型，干最传统的求神拜佛。只要 AI 算出今天宜摆烂，你就心安理得地原地躺平。",
        "why": "你要的不是严格证明，是一个能推你动起来的答案。",
        "strengths": ["决策启动快", "擅长借外力破犹豫", "能从模糊答案里读出方向"],
        "risks": ["容易把随机当天意", "对结果过度解读", "逻辑校验偏弱"],
        "palette": {"accent": "#86be80", "soft": "#eef9eb", "ink": "#4d7a47"},
        "illustration": {"skin": "#f0c8a7", "hair": "#79ad6d", "jacket": "#93ca86", "shirt": "#f6fcf2", "pants": "#78996a", "shoe": "#536949", "pose": "oracle", "prop": "crystal"},
    },
    {
        "type": "MUSE",
        "code": "RVAE",
        "nameZh": "意识流艺术家",
        "nameEn": "The Muse Caller",
        "camp": "混沌创造者",
        "campKey": "creators",
        "subtitle": "意识流艺术家",
        "tagline": "需求像降神，幻觉像显灵。",
        "description": "需求极度抽象。比起发指令，你更像是在降神。你面无表情地敲下“画出一种听得见的寂静”，或者“写段有宿命感的代码”，然后在失控的边缘冷眼旁观，等待大模型的幻觉为你显灵。",
        "why": "你靠感觉开路，也愿意把一部分结果交给偶然。",
        "strengths": ["想象力强", "抽象表达能力高", "容易得到意外灵感"],
        "risks": ["复现性差", "需求边界模糊", "容易沉迷偶然惊喜"],
        "palette": {"accent": "#d2a84e", "soft": "#fbf1d9", "ink": "#7b6124"},
        "illustration": {"skin": "#f1c9ab", "hair": "#c2943b", "jacket": "#dfb560", "shirt": "#fff8eb", "pants": "#c39c52", "shoe": "#8a6c2d", "pose": "paint", "prop": "brush"},
    },
    {
        "type": "MEME",
        "code": "DVFE",
        "nameZh": "乐子人",
        "nameEn": "The Meme Smith",
        "camp": "混沌创造者",
        "campKey": "creators",
        "subtitle": "乐子人",
        "tagline": "最强生产力，制造最纯粹的电子垃圾。",
        "description": "拥有顶级的整活能力。让 AI 写林黛玉倒拔垂杨柳的剧本，或者生成朋友长着狗头的奇葩图片。用最强的生产力工具，制造最纯粹的网络电子垃圾。",
        "why": "你对 AI 的核心诉求很简单：好玩，够邪门，最好还能传播。",
        "strengths": ["梗感强", "玩具化能力高", "善于制造传播点"],
        "risks": ["容易跑偏", "沉迷低价值产出", "好玩的东西总比有用的先做"],
        "palette": {"accent": "#d2a15b", "soft": "#faf0df", "ink": "#7b5f2d"},
        "illustration": {"skin": "#f0c7a6", "hair": "#bb8f49", "jacket": "#d7ad69", "shirt": "#fff7ef", "pants": "#bb9051", "shoe": "#886731", "pose": "laugh", "prop": "mask"},
    },
    {
        "type": "DIST",
        "code": "DPFL",
        "nameZh": "蒸馏大师",
        "nameEn": "The Distiller",
        "camp": "混沌创造者",
        "campKey": "creators",
        "subtitle": "蒸馏大师",
        "tagline": "把草台班子蒸成几个可执行 Skill。",
        "description": "热衷于信息脱水。把老板的长篇大论蒸馏成三行指令，把同事的甩锅邮件提纯出底层逻辑。你不仅蒸馏别人，还写 Prompt 让 AI 反向蒸馏你自己，致力于把整个草台班底浓缩成几个可执行的 Skill。",
        "why": "你最烦废话。你要的是压缩、提纯、马上能执行。",
        "strengths": ["提炼能力强", "信息压缩极快", "能把混乱转成行动项"],
        "risks": ["容易过度简化", "对背景耐心不足", "显得过于冷酷"],
        "palette": {"accent": "#c6984f", "soft": "#f9eedb", "ink": "#765722"},
        "illustration": {"skin": "#efc4a1", "hair": "#b7853f", "jacket": "#d1a45a", "shirt": "#fff8ef", "pants": "#b18443", "shoe": "#7b5b29", "pose": "stack", "prop": "papers"},
    },
    {
        "type": "BABY",
        "code": "RPAE",
        "nameZh": "电子妈宝",
        "nameEn": "The Eternal Child",
        "camp": "混沌创造者",
        "campKey": "creators",
        "subtitle": "电子妈宝",
        "tagline": "你说我该买那个包吗？",
        "description": "像极了每天准点在家庭群里问晚上吃什么的模样，你也会冷不丁在对话框甩出一句毫无上下文的疑问：\"你说我该买那个包吗？\"没关系，你的 AI 妈妈会稳稳地接住你。",
        "why": "只要生活出现岔路，你就想先把问题甩给一个会回话的东西。",
        "strengths": ["善用外部支持", "决策启动门槛低", "愿意及时求助"],
        "risks": ["自主判断被稀释", "容易形成依赖回路", "日常选择感越来越弱"],
        "palette": {"accent": "#d7a64b", "soft": "#fbf1dc", "ink": "#7d6125"},
        "illustration": {"skin": "#f0c7a8", "hair": "#c2943c", "jacket": "#e0b25d", "shirt": "#fff9ed", "pants": "#c79851", "shoe": "#8b6a2f", "pose": "question", "prop": "bag"},
    },
]

scoring_rules = {
    "version": 2,
    "axes": axes,
    "questionsPerAxis": 5,
    "optionScoreRule": "每题 3 个选项：强指向选项给单侧 2 分，混合选项给轴两侧各 1 分。",
    "resolutionRule": {
        "step1": "先比较每个维度左右两侧总分，高者胜出。",
        "step2": "若平分，则比较该侧拿到 2 分的次数。",
        "step3": "若仍平分，则使用该轴默认倾向。",
        "step4": "按 relationship, input, economy, tolerance 四轴顺序拼接代码。",
    },
    "codeOrder": ["relationship", "input", "economy", "tolerance"],
    "mapping": {
        "DPFE": "POOR",
        "RPAL": "RICH",
        "DPAE": "MAIN",
        "DVAE": "LAZY",
        "DVAL": "PUAA",
        "DPAL": "CTRL",
        "RPFE": "ROLL",
        "DVFL": "FACT",
        "RPFL": "NICE",
        "RVAL": "HEAL",
        "RVFL": "SOUL",
        "RVFE": "PRAY",
        "RVAE": "MUSE",
        "DVFE": "MEME",
        "DPFL": "DIST",
        "RPAE": "BABY",
    },
}

for name, payload in {
    "site-copy.json": site_copy,
    "question-workbench.json": question_workbench,
    "questions.json": questions,
    "personality-types.json": personalities,
    "scoring-rules.json": scoring_rules,
}.items():
    (root / name).write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
